# 2014/4/14
# NLAN Environment 
#

import os

# Note:
# NLAN modules sometimes refer to "__n__" built-in variable
# that is dynamically generated by nlan-agent.py.
# "__n__" includes a platform type and NLAN module directories.
#

# NLAN Master Home Directory
NLAN_DIR = '/root/neutron-lan/nlan'

# Directory of NLAN agent scripts including NLAN modules
NLAN_SCP_DIR = os.path.join(NLAN_DIR, 'agent') 

# nlan-ssh script file
NLAN_SSH = os.path.join(NLAN_DIR, 'nlan_ssh.py')

# roster file 
ROSTER_YAML = os.path.join(NLAN_DIR,'roster.yaml')

# NLAN Agent Home Directory
NLAN_AGENT_DIR = '/opt/nlan'

# NLAN agent script file
NLAN_AGENT = os.path.join(NLAN_AGENT_DIR,'nlan_agent.py')

# NLAN libraries used by NLAN Agent and NLAN modules
NLAN_LIBS = ['oputil.py', 'cmdutil.py']

# NLAN module directories
NLAN_MOD_DIRS = ['command', 'config']

# OVSDB schema file with NLAN-related addition
SCHEMA = 'vswitch.schema_2.0.0'

# List indexes for NLAN "dvsdvr" state 
# TODO: dynamically generate this from the OVSDB schema
INDEXES = {'subnets': 'vni', 'services': 'name'}

# "dvsdvr" state order (rule: lower states depend on upper states)
# TODO: dynamically generate this from the OVSDB schema
STATE_ORDER = ['bridges', 'services', 'gateway', 'vxlan', 'subnets']

