# 2014/2/5
# OpenWRT DVS/DVR YAML config file
# 
# TODO: "jinja2" template manipulation. 

openwrt1:
   bridges: true 
   vxlan:
      local_ip: '192.168.57.101'
      remote_ips:
         - '192.168.57.102'
         - '192.168.57.103'
   subnets:
      - vid: '1'
        vni: '101'
        ip_dvr: '10.0.1.1/24'
        ip_vhost: '10.0.1.101/24'
      - vid: '3'
        vni: '103'
        ip_dvr: '10.0.3.1/24'
        ip_vhost: '10.0.3.101/24'

openwrt2:
   bridges: true 
   vxlan:
      local_ip: '192.168.57.102'
      remote_ips:
         - '192.168.57.101'
         - '192.168.57.103'
   subnets:
      - vid: '1'
        vni: '101'
        ip_dvr: '10.0.1.1/24'
        ip_vhost: '10.0.1.102/24'
      - vid: '3'
        vni: '103'
        ip_dvr: '10.0.3.1/24'
        ip_vhost: '10.0.3.102/24'

openwrt3:
   bridges: true 
   vxlan:
      local_ip: '192.168.57.103'
      remote_ips:
         - '192.168.57.101'
         - '192.168.57.102'
   subnets:
      - vid: '1'
        vni: '101'
        ip_dvr: '10.0.1.1/24'
        ip_vhost: '10.0.1.103/24'
      - vid: '3'
        vni: '103'
        ip_dvr: '10.0.3.1/24'
        ip_vhost: '10.0.3.103/24'


