# 2014/2/6
# Roster of OpenWRT routers. 
#

openwrt1:
   host: 192.168.56.111
   user: root
   passwd: root

openwrt2:
   host: 192.168.56.112
   user: root
   passwd: root

openwrt3:
   host: 192.168.56.113
   user: root
   passwd: root



